#!/usr/bin/env bash
# Deploy weftspun_studio, its CockroachDB host, and usd_viewer_app
# as Podman quadlets. RFD 0058. RFD 0120 split those three apps into
# their own repos (weftspun-studio, weftspun-character-taxonomy,
# weftspun-usd-viewer); this script, and the one shared unit,
# weftspun.network, moved into weftspun-studio, the app that
# requires the other two reachable. No systemd oneshot or
# hand-written .service units — every unit here is generated by
# podman-system-generator from a .container/.volume/.network/.build
# file.
#
# Usage: sudo bash scripts/deploy-weftspun-quadlet.sh
#
# Syncs this repo to /opt/weftspun/weftspun-studio, clones or pulls
# weftspun-usd-viewer to /opt/weftspun/weftspun-usd-viewer (the
# build context each app's own .build unit points at), installs the
# quadlet files, and lets systemd build and start every container.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OPT_DIR="/opt/weftspun"
STUDIO_DIR="$OPT_DIR/weftspun-studio"
USD_VIEWER_DIR="$OPT_DIR/weftspun-usd-viewer"
USD_VIEWER_REMOTE="https://github.com/weftspun/weftspun-usd-viewer.git"
QUADLET_DIR="/etc/containers/systemd"

if [[ $EUID -ne 0 ]]; then
  echo "run as root: sudo bash $0" >&2
  exit 1
fi

if ! command -v podman &>/dev/null; then
  echo "podman not found" >&2
  exit 1
fi

cgroups_version="$(podman info --format '{{.Host.CgroupsVersion}}')"
if [[ "$cgroups_version" != "v2" ]]; then
  echo "quadlet needs cgroups v2, host reports $cgroups_version" >&2
  exit 1
fi

# --- sync source ------------------------------------------------------
# The .build quadlets read each Dockerfile from a fixed path, so
# every repo has to live somewhere stable regardless of where it was
# cloned for development.

mkdir -p "$OPT_DIR"
rsync -a --delete \
  --exclude '_build' --exclude 'deps' --exclude '.git' \
  --exclude 'burrito_out' --exclude 'node_modules' --exclude '.crdb' \
  "$ROOT/" "$STUDIO_DIR/"
echo "synced $ROOT -> $STUDIO_DIR"

if [[ -d "$USD_VIEWER_DIR/.git" ]]; then
  git -C "$USD_VIEWER_DIR" pull --ff-only
else
  git clone "$USD_VIEWER_REMOTE" "$USD_VIEWER_DIR"
fi
echo "synced $USD_VIEWER_REMOTE -> $USD_VIEWER_DIR"

# --- quadlet units ------------------------------------------------------
# One shared network, from this repo, plus each app's own build,
# container, and volume units from its own synced deploy/quadlet/.

mkdir -p "$QUADLET_DIR"
install -m 0644 "$ROOT"/deploy/quadlet/weftspun.network "$QUADLET_DIR/"
for app_dir in "$STUDIO_DIR" "$USD_VIEWER_DIR"; do
  for ext in volume build container; do
    for unit in "$app_dir"/deploy/quadlet/*."$ext"; do
      [[ -e "$unit" ]] || continue
      install -m 0644 "$unit" "$QUADLET_DIR/"
    done
  done
done

systemctl daemon-reload

# Quadlet honors each unit's own [Install] section at generation time
# — `systemctl enable` is for a hand-written unit's symlinks, and
# refuses on a generated one ("transient or generated"). `start` is
# the right verb here; the WantedBy= lines already wired the boot-time
# enablement when daemon-reload ran the generator.
#
# weftspun.service pulls in weftspun-crdb.service and
# weftspun-usd-viewer.service via Requires=/After=, and each pulls in
# its own .build/.volume/.network units automatically, so starting
# weftspun.service alone brings the whole stack up. The first start
# builds every image, which is slower than a normal systemd start —
# TimeoutStartSec=120 in weftspun.container covers it.
systemctl start weftspun.service

echo "=== weftspun.service ==="
systemctl --no-pager status weftspun.service || true
echo "=== weftspun-crdb.service ==="
systemctl --no-pager status weftspun-crdb.service || true
echo "=== weftspun-usd-viewer.service ==="
systemctl --no-pager status weftspun-usd-viewer.service || true
